package acme:app@0.0.1;

interface external-function {
    record external-input {
        name: string, 
    }
    handle: func(input: external-input) -> result<string, string>;
}

interface acme-interface {
    record acme-input {
        name: string, 
    }
    handle: func(input: acme-input) -> result<string, string>;
}

world acme-world-no-serde {
    import external-function;
    import wasmcloud:messaging/consumer@0.2.0;
}

world acme-world-serde {
    export acme-interface;
    import external-function;
}